[global]
sources_list = "./sources.list"
extra_key_paths = []
arches = [
     "amd64",
     "arm64",
     "armhf",
     "i386",
     "ppc64el",
     "riscv64",
     "s390x",
]
port = 9393
template_dir = "."
enable_metrics = false
